import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {
        zIndex: -1000,
        alignItems: 'center',
        flex: 1,
        backgroundColor: 'lightgray',
    },
    newView: {
        borderRadius: 10,
        backgroundColor: '#e5e5e5',
        padding: 10,
    },
    headerButtons: {
        marginTop: 35,
        width: '100%',
        maxWidth: 310,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        borderRadius: 5,
    },
    text: {
        fontSize: 16,
    },
    notificationContainer: {
        flexDirection: 'row',
        width: 100,
        justifyContent: 'space-between',
    },
    daysRiddlesProposalContainer: {
        marginTop: 25,
        width: 310,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    weeklyRiddlesChallengesButtonsContainer: {
        marginTop: 25,
        width: 310,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    starButton: {
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        width: 71,
        height: 40,
        padding: 10,
        backgroundColor: '#F8B469',
        borderRadius: 15,
    },
    bellButton: {
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        width: 40,
        height: 40,
        padding: 10,
        backgroundColor: '#fff',
        borderRadius: 14,
    },
    bellButtonNotifications: {
        position: 'absolute',
        top: -6,
        fontWeight: 'bold',
        right: -6,
        width: 24,
        height: 22,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bellButtonText: {
        fontSize: 11,
        color: '#fff',
        fontWeight: 'bold',
    },
    lampButton: {
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        width: 40,
        height: 40,
        padding: 10,
        backgroundColor: '#fff',
        borderRadius: 14,
    },
    lampButtonNotifications: {
        position: 'absolute',
        top: -6,
        fontWeight: 'bold',
        right: -6,
        width: 24,
        height: 22,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    lampButtonText: {
        fontSize: 11,
        color: '#fff',
        fontWeight: 'bold',
    },
    starIcon: {
        marginTop: 3,
    },
    iconContainer: {
        marginRight: 5,
    },
    iconsSpecialBrand: {
        width: 24,
        height: 24,
        borderRadius: 8,
    },
    starText: {
        fontWeight: 600,
        color: '#fff',
        fontSize: 11,
    },
    weeklyRiddleContainer: {
        marginTop: 20,
        height: 200,
        borderRadius: 32,
        borderStyle: 'solid',
        borderWidth: 2,
        borderColor: '#f6f6f6',
        backgroundColor: '#fff',
        width: 310,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    specialBrandRiddleContainer: {
        marginTop: 20,
        height: 200,
        borderRadius: 32,
        borderStyle: 'solid',
        borderCurve: 1,
        borderWidth: 2,
        borderColor: '#f6f6f6',
        backgroundColor: '#fff',
        width: 310,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    iconsSpecialBrandContainer: {
        flexDirection: 'row',
        marginTop: 10,
        width: 100,
        justifyContent: 'space-between',
    },
    weeklyRiddleMainTitle: {
        width: 100,
        marginTop: 20,
        marginLeft: 20,
        fontSize: 24,
        color: '#3D444F',
        lineHeight: 30,
        letterSpacing: -0.24,
    },
    expDaysRiddleMainTitle: {
        width: 100,
        fontSize: 14,
        marginTop: 36,
        color: '#3D444F',
        lineHeight: 20,
        letterSpacing: -0.14,
    },
    specialRiddlesMainTitle: {
        width: 120,
        fontSize: 16,
        marginTop: 5,
        fontWeight: 800,
        color: '#3D444F',
        lineHeight: 20,
        letterSpacing: -0.16,
    },
    specialRiddleSubTitle: {
        width: 120,
        marginTop: 20,
        fontWeight: 'normal',
        fontSize: 12,
        color: '#5F6F89',
    },
    weeklyRiddleSubTitle: {
        width: 120,
        marginLeft: 20,
        marginTop: 20,
        fontWeight: 'normal',
        fontSize: 12,
        color: '#5F6F89',
    },
    expDaysRiddleSubTitle: {
        marginTop: 14,
        width: 100,
        fontWeight: 'normal',
        fontSize: 12,
        color: '#5F6F89',
    },
    weeklyDescription: {
        padding: 20,
    },
    weeklyRiddleImageContainer: {
        zIndex: 1000,
        position: 'absolute',
        top: 0,
        right: -26,
        width: 213,
        height: 163,
    },
    specialBrandGiftImage: {
        width: 120,
        height: 111,
        top: 45,
        right: 60,
        zIndex: 1000,
        transform: [{rotate: '-3deg'}],
    },
    specialBrandBrandingImage: {
        transform: [{rotate: '8deg'}],
        position: 'absolute',
        top: -15,
        right: -40,
        width: 177,
        height: 177,
    },
    expRiddleImageContainer: {
        zIndex: 1000,
        position: 'absolute',
        top: -20,
        right: -13,
        width: 95,
        height: 95,
    },
    expRiddleOneImageContainer: {
        zIndex: 1000,
        position: 'absolute',
        top: -20,
        right: -13,
        width: 82,
        height: 120,
    },
    weeklyRiddleImageMask: {
        position: 'absolute',
        zIndex: 1000,
        top: -1.5,
        right: -1.5,
        width: 213,
        height: 163,
        opacity: 0.7,
        borderRadius: 32,
    },
    expRiddleImageMask: {
        position: 'absolute',
        zIndex: 1000,
        top: -25,
        right: -25,
        width: 171,
        height: 191,
        opacity: 0.7,
        borderRadius: 32,
    },
    expRiddleContainer: {
        width: 147,
        height: 168,
        borderRadius: 32,
        borderStyle: 'solid',
        borderCurve: 1,
        borderWidth: 2,
        borderColor: '#f6f6f6',
        backgroundColor: '#fff',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    bottomNavContainer: {
        position: 'absolute',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: 310,
        marginBottom: 15,
        bottom: 0,
    },
    bottomNavContainerButtonText: {
        fontSize: 12,
        color: '#3D444F',
        fontWeight: 'bold',
    },
    bottomNavContainerButtonTextDisabled: {
        fontSize: 12,
        color: '#8f9ab1',
        fontWeight: 'bold',
    },
    navButton: {
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 5,
    },
    riddleChallengesButton: {
        width: 70,
        backgroundColor: '#F8F9FD',
        padding: 10,
        height: 42,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#171717',
        shadowOffset: {width: -1, height: 4},
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 2,
        borderColor: '#F8F9FD',
        borderWidth: 1,
    },
    riddleChallengesButtonText: {
        color: '#aaafb8',
        fontSize: 14,
        fontWeight: 'bold',
    },
    riddleChallengesButtonActive: {
        height: 42,
        width: 70,
        backgroundColor: '#F8F9FD',
        padding: 10,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: '#7ACA40',
        borderWidth: 1,
        shadowColor: '#48ff00',
        shadowOffset: {height: 5},
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 20,
    },
    riddleChallengesButtonTextActive: {
        color: '#7ACA40',
        fontSize: 14,
        fontWeight: 'bold',
    },
    riddleChallengesDescription: {
        width: 310,
        marginTop: 43,
    },
    riddleChallengesDescriptionMainTitle: {
        fontSize: 24,
        color: '#3D444F',
        fontWeight: 'bold',
        marginBottom: 17,
        lineHeight: 30,
        letterSpacing: -0.24,
    },
    riddleChallengesDescriptionText: {
        fontSize: 14,
        color: '#5f6f89',
        lineHeight: 20,
        letterSpacing: -0.14,
    },
    riddleChallengesDescriptionSubTitle: {
        fontSize: 15,
        color: '#5f6f89',
        fontWeight: 'bold',
        marginTop: 17,
        lineHeight: 20,
        letterSpacing: -0.14,
    },
    inputQuizContainer: {
        backgroundColor: '#F1F3FF',
        padding: 26,
        width: 310,
        height: 72,
        marginTop: 20,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#f6f6f6',
        borderRadius: 26,

    },
    submitQuizButton: {
        backgroundColor: '#e7e700',
        width: 310,
        height: 72,
        borderRadius: 33,
        shadowColor: '#48ff00',
        shadowOffset: {height: 5},
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 5,
    },
    submitQuizButtonDisabled: {
        opacity: 0.5,
    },
    submitQuizButtonText: {
        fontSize: 16,
        color: '#fff',
        textAlign: 'center',
        marginTop: 23,
    },
    quizAnswer: {
        fontSize: 14,
        color: '#8e9ab1',
        textAlign: 'center',
        marginTop: 20,
    },
});

export default styles;
